remote_theme: thelehhman/texture

title: Nohil Park's Blog
author: Nohil Park
email: pnoil2588@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Personal blog for everything
show_excerpts: true # set to true to show excerpts on the homepage
url: "https://pnoil2588.github.io"
baseurl: "" # /texture


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Nohil Park's Blog
  tagline: ph.D student at SNU
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    # twitter: thelehhman
    github: pnoil2588
    # linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
