remote_theme: murraco/jekyll-theme-minimal-resume

# Site settings
title: Nohil Park's Blog
description: Blog description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pnoil2588.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nohil Park
user_description: Ph.D student
user_title: Software Engineer
email: pnoil2588@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

